nhs-digital-gp-it-futures/OrderFormAcceptanceTests

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Dashboard.cs
- src/OrderFormAcceptanceTests.Tests/Features/DisplayNameAndOrganisation.feature
assert the logged in text is displayed
[AB#6665](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6665)
[AB#6799](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6799)
> 6665: Display Buyer logged in Display Name and Organisation Name

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CreateAnOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm.feature
[AB#5321](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5321)
[AB#6806](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6806)
> 5321: Display order form description section

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Utils/ElementExtensions.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderFormDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CreateAnOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CallOffOrderingParty.feature
[AB#6967](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6967)
[AB#4614](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4614)
> 4614: Display Order Form - Call Off Ordering Party 

- src/OrderFormAcceptanceTests.Actions/Collections/PageActionCollection.cs
- src/OrderFormAcceptanceTests.Actions/PageActions.cs
- src/OrderFormAcceptanceTests.Actions/Pages/Dashboard.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/PageObjects.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderFormDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CreateAnOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Dashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Login_Authorisation.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ViewOrders.feature
[AB#4826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4826)
[AB#6797](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6797)
> 4826: Buyer View Orders

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/OrderDescription.feature
implemented scenario to check details on dashboard after saving
[AB#6812](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6812)
[AB#5161](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5161)
> 5161: Save order

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.TestData/Address.cs
- src/OrderFormAcceptanceTests.TestData/Contact.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CallOffOrderingParty.feature
[AB#7142](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7142)
[AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
> 4615: Autopopulate Call Off Ordering Party information 

- src/OrderFormAcceptanceTests.Actions/Pages/Authentication.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.TestData/Address.cs
- src/OrderFormAcceptanceTests.TestData/Contact.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CallOffOrderingParty.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
Tests are currently ignored because the GET summary hasnt been updated to include the new sections yet
[AB#7145](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7145)
> 4620: Display Order Form - Supplier

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CallOffOrderingParty.feature
Implemented tests, but can't run them until we stop getting the canned data
[AB#7144](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7144)
> 4616: Edit Call Off Ordering Party section

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
- src/OrderFormAcceptanceTests.Tests/OrderFormAcceptanceTests.Tests.csproj
[AB#7146](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7146)
> 4840: Search for a Supplier

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
[AB#7147](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7147)
> 5112: Select a Supplier

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
[AB#7148](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7148)
> 4621: Edit Supplier section - first time

- src/OrderFormAcceptanceTests.Actions/Collections/PageActionCollection.cs
- src/OrderFormAcceptanceTests.Actions/PageActions.cs
- src/OrderFormAcceptanceTests.Actions/Pages/CommencementDate.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/PageObjects.cs
- src/OrderFormAcceptanceTests.Objects/Pages/CommencementDate.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommencementDate.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CreateAnOrder.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CommencementDate.feature
[AB#4617](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4617)
[AB#7150](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7150)
[AB#4619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4619)
[AB#7151](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7151)
> 4617 & 4619 - Commencement Dates

- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
[AB#7421](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7421)
> 7046: Supplier section complete - visit search supplier and select supplier pages

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommencementDate.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipents.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CommencementDate.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
[AB#7542](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7542)
> 4623: Display Order Form - Service Recipients

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipents.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.TestData/ServiceRecipient.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
Implemented as far as I can, we will most probably need to update some locators, the steps around checking the organisation name and ODS code are suspect.
Tests ignored for now, will put ticket back into new and block it until FE work complete
[AB#7543](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7543)
> 7412: User Story 7412: Select Service Recipients - Call Off Ordering Party

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
enabled half the tests, issue with the summary logic
[AB#7534](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7534)
> 7412: Select Service Recipients - Call Off Ordering Party

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.TestData/ServiceRecipient.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7544](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7544)
> 4629: display catalogue solutions

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.Steps/Utils/EnvironmentVariables.cs
- src/OrderFormAcceptanceTests.TestData/ServiceRecipient.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
[AB#7545](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7545)
> 4631: manage catalogue solutions

- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7648](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7648)
> 7261: Add a single Catalogue Solution - select Service Recipient

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
[AB#7548](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7548)
> 7230: Deselect Service Recipient with no Catalogue Solution or Additional Service

- src/OrderFormAcceptanceTests.Steps/Steps/Login_Authorisation.cs
Story: [AB#7395](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7395)
Task: [AB#7712](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7712)
> 7395: AC tests

- azure-pipelines.yml
- domain-template.yaml
[AB#8010](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8010)
> added new environment hosts handling

- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7547](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7547)
> 7826: Add a single Catalogue Solution - select price - split

- src/OrderFormAcceptanceTests.TestData/ServiceRecipient.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7648](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7648)
> 7839: Add a single Catalogue Solution - select Service Recipient - split

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#7877](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7877)
Outstanding work needed to setup the data. I'm not sure what the out from the add price for catalogue solution is going to be at this time. Ideally I want story 8119 finished so I can manually save the page and see what tables are populated.
> 8122: Preview Order Summary 

- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#7877](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7877)
> 8122: Preview Order Summary

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Utils/EnvironmentVariables.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#7885](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7885)
> 8124: Order items (recurring cost) - Catalogue Solution - Flat Variable (On-demand) order type - split

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#8133](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8133)
[AB#5123](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5123)
> Adding additional service display tests

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7865](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7865)
> 8121: Manage Catalogue Solution - Catalogue Solution added - split

- src/OrderFormAcceptanceTests.Actions/Collections/PageActionCollection.cs
- src/OrderFormAcceptanceTests.Actions/PageActions.cs
- src/OrderFormAcceptanceTests.Actions/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/PageObjects.cs
- src/OrderFormAcceptanceTests.Objects/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.TestData/ServiceRecipient.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#5124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5124)
[AB#8154](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8154)
> 5124: Manage Additional Services

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7726](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7726)
Most scenarios are still ignored, whichever price goes in last can untag them
Ran all the variable prices locally and passing, see ticket for screenshots from manual testing
> 8119: Edit a single Catalogue Solution - Flat List Price - Variable (on-demand) - splitx2

- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#7860](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7860)
[AB#7891](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7891)
> 7405: Edit a single Catalogue Solution - Flat List Price - Variable (Patient numbers)

- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8165](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8165)
> 5352: Select Additional Service - AC tests

- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
Tests run, couple of blocking dev tasks mean tests are ignored
[AB#7894](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7894)
[AB#7888](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7888)
> 7694: Order items (recurring cost) - Catalogue Solution - Flat Declarative order type

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8409](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8409)
> 4829: Display Order Form - Associated Services

- src/OrderFormAcceptanceTests.Actions/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Objects/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#7265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7265)
[AB#8332](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8332)
> 7265: Add a single Additional Service - select Service Recipient

- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8416](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8416)
> 5115: Manage Associated Services on a dashboard

- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8425](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8425)
all tests ignored whilst waiting test data and dev work
> 5351: Add a single Associated Service - Select Associated Service

- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8437)
> 7072: Add a single Associated Service - Select price

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#7569](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7569)
> 7569: Edit a single Associated Service - Flat list price - Variable (on-demand)

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8448](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8448)
> 4832: Edit a single Associated Service - Flat list price - Declarative

- src/OrderFormAcceptanceTests.Actions/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Utils/DriverExtensions.cs
- src/OrderFormAcceptanceTests.Objects/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#7580](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7580)
[AB#8286](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8286)
> 7580: Edit a single Additional Service - Flat List Price - Variable (On-demand)

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
> 7048: Manage Associated Services on a dashboard - Associated Service Added

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8425](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8425)
> 5351: User Story 5351: Add a single Associated Service - Select Associated Service

- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8437)
> 7072: User Story 7072: Add a single Associated Service - Select price

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#8290](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8290)
[AB#8294](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8294)
> Add additional scenarios for other pricing types

- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8457](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8457)
> 7048: User Story 7048: Manage Associated Services on a dashboard - Associated Service Added

- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#8448](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8448)
> 4832: User Story 4832: Edit a single Associated Service - Flat list price - Declarative

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/FundingSource.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/FundingSource.feature
[AB#8594](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8594)
Task bug raised which is why final scenario is ignored, first won't be available until next page is delivered
> 5436: Display Order Form - Funding Source

- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/FundingSource.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/FundingSource.feature
[AB#8613](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8613)
> 5437: Edit Funding Source section

- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SubmitOrder.feature
[AB#8680](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8680)
> 5291: Display Order Form - Enable Submit Button

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/OrderItem.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
Story: [AB#7692](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7692)
Task: [AB#8684](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8684)
> 8684: Added test for associated service declarative in order summary

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
Story: [AB#7696](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7696)
Task: [AB#8693](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8693)
> 8693: Added tests for associated service on demand in order summary

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
Story: [AB#7725](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7725)
Task: [AB#8696](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8696)
> 7725: Order Items sort AC tests

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/OrderItemList.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#8688](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8688)
> User Story 7693: Total one-off cost

- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/SupplierInfo.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#8799](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8799)
> 7703: Total cost of contract

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#8803](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8803)
> 8719: Order items (recurring cost) - sort alphabetically by item name

- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#8801](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8801)
> 7729: Order items (one-off cost) - sort alphabetically by item name

- src/OrderFormAcceptanceTests.Actions/Collections/PageActionCollection.cs
- src/OrderFormAcceptanceTests.Actions/PageActions.cs
- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/PageObjects.cs
- src/OrderFormAcceptanceTests.Objects/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SubmitOrder.feature
[AB#8805](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8805)
Tests ignored waiting for dev complete
> 5145: Complete Order - If Funding Source is Yes

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Objects/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SubmitOrder.feature
[AB#8807](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8807)
Tests ignored waiting on dev work to complete
Still waiting on data-test-ids
Spoke to Sam M and it will be the same id for the content holder for both Yes/No funding source content so updated that
> 8735: Complete Order - If Funding Source is No

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CreateAnOrder.cs
- src/OrderFormAcceptanceTests.Tests/Features/CreateAnOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CommencementDate.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/FundingSource.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SubmitOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
[AB#8811](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8811)
> 8758: Update label on Submit order button on Order dashboard

- src/OrderFormAcceptanceTests.Objects/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
[AB#8813](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8813)
> 8774: Update content on Organisation's Orders dashboard

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/Pages/PrintOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/PrintOrder.feature
Story [AB#8736](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8736)
Task [AB#8809](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8809)
> 8736: Added tests for order summary printing

- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/DeleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/DeleteOrder.cs
- src/OrderFormAcceptanceTests.Tests/Features/DeleteOrder.feature
[AB#8817](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8817)
> 5287: Delete an Order

- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
Story [AB#8741](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8741)
Task  [AB#9081](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9081)
> 8741: AC tests

- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ContextKeys.cs
- src/OrderFormAcceptanceTests.Steps/Steps/DeleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/FundingSource.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/DeleteOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CallOffOrderingParty.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CommencementDate.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/FundingSource.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/OrderDescription.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/ServiceRecipients.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/SupplierInformation.feature
- src/OrderFormAcceptanceTests.Tests/Features/OrganisationOrderDashboard.feature
- src/OrderFormAcceptanceTests.Tests/Features/ViewOrders.feature
Story: [AB#6859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6859)
Task: [AB#9077](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9077)
> Dashboard status grouping AC tests

- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
[AB#9098](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9098)
> 9045: Get order summary (PDF) - order Complete

- src/OrderFormAcceptanceTests.Actions/Collections/PageActionCollection.cs
- src/OrderFormAcceptanceTests.Actions/PageActions.cs
- src/OrderFormAcceptanceTests.Actions/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Objects/Collections/PageCollection.cs
- src/OrderFormAcceptanceTests.Objects/PageObjects.cs
- src/OrderFormAcceptanceTests.Objects/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.Tests/Features/PreviewOrderSummary.feature
Story [AB#8739](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8739)
Task [AB#9085](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9085)
> 8739: AC tests for Preview Order Summary

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Objects/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
[AB#9312](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9312)
> 9256: Add Continue editing order button

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/FundingSource.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#9316](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9316)
A dodgy merge removed the scenario changes to the catalogue solutions feature file
Also made more changes to reflect how the system actually is
> 6271: BULK ORDERING - Order dashboard - no Service Recipient section & enable catalogue solution

- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.TestData/SupplierInfo.cs
[AB#9330](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9330)
> 9228: BULK ORDERING - Add a Catalogue Solution - one list price

- charts/of-ac-tests/templates/job.yaml
- entrypoint.sh
Forgot to add in the specific config for the various DB's
> Update helm config

- src/OrderFormAcceptanceTests.Actions/Pages/CommencementDate.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrganisationsOrdersDashboard.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#10328](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10328)
[AB#9985](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9985)
> 10328: Update tests for per patient bulk ordering

- azure-pipelines.yml
- docker-compose-pipeline.yml
- src/OrderFormAcceptanceTests.Actions/Pages/Authentication.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/OrderFormAcceptanceTests.Steps.csproj
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.TestData/OrderFormAcceptanceTests.TestData.csproj
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
- src/OrderFormAcceptanceTests.Tests/OrderFormAcceptanceTests.Tests.csproj
[AB#10509](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10509)
[AB#10259](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10259)
> 10509: Edit catalogue solution

- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#10516](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10516)
[AB#10746](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10746)
> 10516: Edit Solution

- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.TestData/SupplierInfo.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#10552](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10552)
[AB#10839](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10839)
> 10552: Only Published Items displayed

- src/OrderFormAcceptanceTests.Actions/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Objects/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#10035](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10035)
[AB#11075](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11075)
> 10035: Service Instance ID

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#9536](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9536)
[AB#11667](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11667)
> 9536: Multiple order items in alphabetical order

- src/OrderFormAcceptanceTests.Actions/Pages/Authentication.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#11143](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11143)
> 11143: 4dp max update

- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#12231](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12231)
[AB#11173](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11173)
[AB#12232](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12232)
[AB#11743](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11743)
[AB#12233](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12233)
[AB#11746](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11746)
> Enable other price type Catalogue Solutions tests

- azure-pipelines.yml
- src/OrderFormAcceptanceTests.Objects/Pages/Homepage.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CallOffOrderingParty.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/DeleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/FundingSource.cs
- src/OrderFormAcceptanceTests.Steps/Steps/SupplierInformation.cs
- src/OrderFormAcceptanceTests.TestData/Order.cs
- src/OrderFormAcceptanceTests.TestData/OrderFormAcceptanceTests.TestData.csproj
- src/OrderFormAcceptanceTests.TestData/OrderHelpers.cs
- src/OrderFormAcceptanceTests.TestData/Utils/Policies.cs
- src/OrderFormAcceptanceTests.TestData/Utils/SqlExecutor.cs
- src/OrderFormAcceptanceTests.Tests/Features/ViewOrders.feature
> Update order create

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#9363](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9363)
[AB#12325](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12325)
> Add service recipient edit test

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#9363](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9363)
[AB#12325](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12325)
> 9363: Edit Service Recipient Tests

- .github/CODEOWNERS
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Actions/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Objects/Pages/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Login_Authorisation.cs
- src/OrderFormAcceptanceTests.TestData/Organisation.cs
Fixes test broken due to accessibility and OF changes. 
Updates codeowners
> Update to fix tests

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/Hooks.cs
- src/OrderFormAcceptanceTests.Steps/Utils/ContextKeys.cs
- src/OrderFormAcceptanceTests.Steps/Utils/TestBase.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/DeleteCatalogueSolution.feature
[AB#9038](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9038)
[AB#13194](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13194)
> 9038: Delete Solution

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.TestData/OrderItemList.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutionAlreadyInOrder.feature
There are 2 Scenarios in this Feature which have been completed.
> The 2 Scenarios are completed

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/OneListPriceForAdditionalService.feature
[AB#9258](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9258)
[AB#13215](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13215)
> Implemented basic scenarios

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/Helpers/OrderHelpers.cs
- src/OrderFormAcceptanceTests.TestData/Helpers/OrderItemHelper.cs
- src/OrderFormAcceptanceTests.TestData/SupplierInfo.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServicesOrdering.feature
[AB#9227](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9227)
[AB#13213](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13213)
> Add additional services ordering scenarios

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CompleteOrder.cs
- src/OrderFormAcceptanceTests.TestData/Helpers/OrderHelpers.cs
- src/OrderFormAcceptanceTests.Tests/Features/CompleteOrder.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
Lots of stories and tasks involved with this. All test were preexisting and just needed tweaks
[AB#9550](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9550)
[AB#13388](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13388)
[AB#9257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9257)
[AB#13217](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13217)
[AB#9271](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9271)
[AB#13453](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13453) …
> Reenable and update additional services tests

- src/OrderFormAcceptanceTests.Actions/Pages/CompleteOrder.cs
[AB#9490](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9490)
[AB#13674](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13674)
> 9490: Update content check for Complete screens when funding is set to yes

- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/PreviewOrderSummary.cs
- src/OrderFormAcceptanceTests.TestData/Helpers/OrderHelpers.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServicesEditRecipients.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/PreviewOrderSummary.feature
[AB#9442](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9442)
[AB#13544](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13544)
> 9442: Add Edit service recipients tests for Additional Services

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
[AB#9448](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9448)
[AB#13847](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13847)
[AB#9451](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9451)
[AB#13850](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13850)
[AB#12919](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12919)
[AB#13853](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13853)
[AB#12920](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12920) …
> Reenable and fix Additional Service On Demand tests

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/OrderForm.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
[AB#13374](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13374)
[AB#13762](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13762)
> basic scenarios for associated services

- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.TestData/SupplierInfo.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CommencementDate.feature
[AB#9454](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9454)
[AB#13938](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13938)
[AB#9455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9455)
[AB#13953](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13953)
Note - I have also fixed a few obvious issues and removed some tests that can't be completed due to the NHS front end library changing the way some components work
> 9454: Additional Services On Demand

- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Steps/Steps/ServiceRecipients.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServicesEditRecipients.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutions.feature
[AB#9453](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9453)
[AB#13859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13859)
> basic scenarios implemented

- src/OrderFormAcceptanceTests.Actions/Pages/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Actions/Pages/OrderForm.cs
- src/OrderFormAcceptanceTests.Objects/Pages/Common.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServicesDelete.feature
[AB#9464](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9464)
[AB#14170](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14170)
> 9464: Delete Additional Service

- src/OrderFormAcceptanceTests.Steps/Steps/AdditionalServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/AssociatedServices.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CatalogueSolutions.cs
- src/OrderFormAcceptanceTests.Steps/Steps/CommonSteps.cs
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AdditionalServicesEditRecipients.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/AssociatedServices.feature
- src/OrderFormAcceptanceTests.Tests/Features/ManageOrderForm/CatalogueSolutionAlreadyInOrder.feature
[AB#9289](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9289)
[AB#14220](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14220)
[AB#13373](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13373)
[AB#14257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14257)
[AB#13376](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13376)
[AB#14111](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14111)
> implemented basic scenarios for 3 tickets & tidied up some old steps
